export type ToolMeta = {
  id: string;
  label: string;
  description: string;
  icon: string;
  route: string;
  accent: string;
  badge: string;
};

export const TOOLS: ToolMeta[] = [
  {
    id: 'basic-calc',
    label: 'Calculator',
    description: 'Standard arithmetic',
    icon: 'calculator-outline',
    route: '/tools/basic-calculator',
    accent: '#3B82F6',
    badge: 'Math',
  },
  {
    id: 'sci-calc',
    label: 'Scientific Calc',
    description: 'Trig, log, powers & more',
    icon: 'flask-outline',
    route: '/tools/scientific-calculator',
    accent: '#6366F1',
    badge: 'Math',
  },
  {
    id: 'emi-calc',
    label: 'EMI Calculator',
    description: 'Loan EMI & schedule',
    icon: 'cash-outline',
    route: '/tools/emi-calculator',
    accent: '#10B981',
    badge: 'Finance',
  },
  {
    id: 'tip-calc',
    label: 'Tip Calculator',
    description: 'Split bills & tips',
    icon: 'restaurant-outline',
    route: '/tools/tip-calculator',
    accent: '#F59E0B',
    badge: 'Finance',
  },
  {
    id: 'unit-conv',
    label: 'Unit Converter',
    description: 'Length, weight, temp…',
    icon: 'swap-horizontal-outline',
    route: '/tools/unit-converter',
    accent: '#14B8A6',
    badge: 'Convert',
  },
  {
    id: 'color-tools',
    label: 'Color Tools',
    description: 'HEX ↔ RGB ↔ HSL',
    icon: 'color-palette-outline',
    route: '/tools/color-tools',
    accent: '#EC4899',
    badge: 'Design',
  },
  {
    id: 'todo',
    label: 'Todo Manager',
    description: 'Tasks with priorities',
    icon: 'checkbox-outline',
    route: '/tools/todo-manager',
    accent: '#8B5CF6',
    badge: 'Tasks',
  },
  {
    id: 'stopwatch',
    label: 'Stopwatch & Timer',
    description: 'Laps & countdown',
    icon: 'timer-outline',
    route: '/tools/stopwatch-timer',
    accent: '#F97316',
    badge: 'Time',
  },
  {
    id: 'password',
    label: 'Password Gen',
    description: 'Secure random passwords',
    icon: 'key-outline',
    route: '/tools/password-generator',
    accent: '#EF4444',
    badge: 'Security',
  },
  {
    id: 'bmi-calc',
    label: 'BMI Calculator',
    description: 'Body mass index',
    icon: 'body-outline',
    route: '/tools/bmi-calculator',
    accent: '#06B6D4',
    badge: 'Health',
  },
  {
    id: 'age-calc',
    label: 'Age Calculator',
    description: 'Exact age & birthday',
    icon: 'calendar-outline',
    route: '/tools/age-calculator',
    accent: '#84CC16',
    badge: 'Date',
  },
  {
    id: 'markdown',
    label: 'Markdown Notepad',
    description: 'Write & preview notes',
    icon: 'document-text-outline',
    route: '/tools/markdown-notepad',
    accent: '#64748B',
    badge: 'Notes',
  },
  {
    id: 'notes',
    label: 'Note Cards',
    description: 'Colorful notes with PIN lock',
    icon: 'reader-outline',
    route: '/tools/notes',
    accent: '#F59E0B',
    badge: 'Notes',
  },
  {
    id: 'weather',
    label: 'Weather',
    description: 'Live weather & 7-day forecast',
    icon: 'partly-sunny-outline',
    route: '/tools/weather',
    accent: '#3B82F6',
    badge: 'Live',
  },
  {
    id: 'investment',
    label: 'Investment Calc',
    description: 'SIP, lumpsum, returns & compare',
    icon: 'trending-up-outline',
    route: '/tools/investment-calculator',
    accent: '#10B981',
    badge: 'Finance',
  },
  {
    id: 'birthday',
    label: 'Birthday Tracker',
    description: 'Never miss a birthday',
    icon: 'gift-outline',
    route: '/tools/birthday-tracker',
    accent: '#F43F5E',
    badge: 'Life',
  },
  {
    id: 'holiday',
    label: 'Holiday Calendar',
    description: 'Holidays & custom events',
    icon: 'flag-outline',
    route: '/tools/holiday-calendar',
    accent: '#8B5CF6',
    badge: 'Calendar',
  },
  {
    id: 'gym',
    label: 'Gym Calendar',
    description: 'Track your workout days',
    icon: 'barbell-outline',
    route: '/tools/gym-calendar',
    accent: '#F97316',
    badge: 'Health',
  },
  {
    id: 'water',
    label: 'Water Tracker',
    description: 'Daily hydration goals',
    icon: 'water-outline',
    route: '/tools/water-tracker',
    accent: '#0EA5E9',
    badge: 'Health',
  },
  {
    id: 'expense',
    label: 'Expense Tracker',
    description: 'Track spending & budgets',
    icon: 'wallet-outline',
    route: '/tools/expense-tracker',
    accent: '#6366F1',
    badge: 'Finance',
  },
  {
    id: 'reminder',
    label: 'Reminders',
    description: 'Set reminders & alerts',
    icon: 'notifications-outline',
    route: '/tools/reminder',
    accent: '#A855F7',
    badge: 'Life',
  },
  {
    id: 'translate',
    label: 'Translate',
    description: 'Translate text between languages',
    icon: 'language-outline',
    route: '/tools/translate',
    accent: '#D946EF',
    badge: 'Language',
  },
  {
    id: 'pomodoro',
    label: 'Pomodoro',
    description: 'Focus timer with work/break cycles',
    icon: 'hourglass-outline',
    route: '/tools/pomodoro',
    accent: '#EF4444',
    badge: 'Productivity',
  },
  {
    id: 'habit-tracker',
    label: 'Habit Tracker',
    description: 'Build daily habits & streaks',
    icon: 'trending-up-outline',
    route: '/tools/habit-tracker',
    accent: '#8B5CF6',
    badge: 'Life',
  },
  {
    id: 'world-clock',
    label: 'World Clock',
    description: 'Time across timezones',
    icon: 'globe-outline',
    route: '/tools/world-clock',
    accent: '#3B82F6',
    badge: 'Time',
  },
  {
    id: 'text-tools',
    label: 'Text Tools',
    description: 'Word count, case convert & more',
    icon: 'text-outline',
    route: '/tools/text-tools',
    accent: '#14B8A6',
    badge: 'Convert',
  },
  {
    id: 'dice-coin',
    label: 'Dice & Coin',
    description: 'Roll dice & flip coins',
    icon: 'dice-outline',
    route: '/tools/dice-coin',
    accent: '#F59E0B',
    badge: 'Fun',
  },
  {
    id: 'percentage-calc',
    label: 'Percentage Calc',
    description: 'Percentages, discounts & changes',
    icon: 'analytics-outline',
    route: '/tools/percentage-calculator',
    accent: '#F97316',
    badge: 'Math',
  },
  {
    id: 'qr-generator',
    label: 'QR Generator',
    description: 'Generate QR codes from text & URLs',
    icon: 'qr-code-outline',
    route: '/tools/qr-generator',
    accent: '#1E293B',
    badge: 'Utility',
  },
  {
    id: 'currency-converter',
    label: 'Currency Convert',
    description: 'Real-time exchange rates',
    icon: 'logo-usd',
    route: '/tools/currency-converter',
    accent: '#059669',
    badge: 'Finance',
  },
  {
    id: 'json-formatter',
    label: 'JSON Formatter',
    description: 'Format, validate & minify JSON',
    icon: 'code-slash-outline',
    route: '/tools/json-formatter',
    accent: '#0EA5E9',
    badge: 'Dev',
  },
  {
    id: 'flashcards',
    label: 'Flashcards',
    description: 'Study cards with flip & decks',
    icon: 'albums-outline',
    route: '/tools/flashcards',
    accent: '#A855F7',
    badge: 'Learning',
  },
  {
    id: 'compass',
    label: 'Compass',
    description: 'Digital compass with heading',
    icon: 'compass-outline',
    route: '/tools/compass',
    accent: '#DC2626',
    badge: 'Utility',
  },
  {
    id: 'loan-comparison',
    label: 'Loan Compare',
    description: 'Compare multiple loans side-by-side',
    icon: 'git-compare-outline',
    route: '/tools/loan-comparison',
    accent: '#7C3AED',
    badge: 'Finance',
  },
  {
    id: 'tally-counter',
    label: 'Tally Counter',
    description: 'Tap to count anything',
    icon: 'add-circle-outline',
    route: '/tools/tally-counter',
    accent: '#0891B2',
    badge: 'Utility',
  },
  {
    id: 'random-picker',
    label: 'Random Picker',
    description: 'Pick random items from a list',
    icon: 'shuffle-outline',
    route: '/tools/random-picker',
    accent: '#D946EF',
    badge: 'Fun',
  },
  {
    id: 'event-countdown',
    label: 'Event Countdown',
    description: 'Countdown to important dates',
    icon: 'hourglass-outline',
    route: '/tools/event-countdown',
    accent: '#E11D48',
    badge: 'Date',
  },
  {
    id: 'breathing',
    label: 'Breathing',
    description: 'Guided breathing exercises',
    icon: 'leaf-outline',
    route: '/tools/breathing',
    accent: '#059669',
    badge: 'Health',
  },
  {
    id: 'ruler',
    label: 'Ruler',
    description: 'On-screen ruler in cm & inches',
    icon: 'resize-outline',
    route: '/tools/ruler',
    accent: '#CA8A04',
    badge: 'Utility',
  },
  {
    id: 'gpa-calc',
    label: 'GPA Calculator',
    description: 'Calculate GPA from grades',
    icon: 'school-outline',
    route: '/tools/gpa-calculator',
    accent: '#2563EB',
    badge: 'Learning',
  },
  {
    id: 'base-converter',
    label: 'Base Converter',
    description: 'Binary, Octal, Decimal & Hex',
    icon: 'git-branch-outline',
    route: '/tools/base-converter',
    accent: '#7C3AED',
    badge: 'Dev',
  },
  {
    id: 'date-calculator',
    label: 'Date Calculator',
    description: 'Days between dates & add/subtract',
    icon: 'calendar-number-outline',
    route: '/tools/date-calculator',
    accent: '#0D9488',
    badge: 'Date',
  },
  {
    id: 'matrix-calc',
    label: 'Matrix Calculator',
    description: 'Add, multiply, determinant & inverse',
    icon: 'grid-outline',
    route: '/tools/matrix-calculator',
    accent: '#4F46E5',
    badge: 'Math',
  },
  {
    id: 'fuel-cost',
    label: 'Fuel Cost',
    description: 'Calculate trip fuel expenses',
    icon: 'speedometer-outline',
    route: '/tools/fuel-cost',
    accent: '#EA580C',
    badge: 'Finance',
  },
  {
    id: 'savings-goal',
    label: 'Savings Goal',
    description: 'Track progress toward savings',
    icon: 'trophy-outline',
    route: '/tools/savings-goal',
    accent: '#16A34A',
    badge: 'Finance',
  },
  {
    id: 'unit-price',
    label: 'Price Compare',
    description: 'Compare unit prices of products',
    icon: 'pricetag-outline',
    route: '/tools/unit-price',
    accent: '#9333EA',
    badge: 'Finance',
  },
  {
    id: 'mood-journal',
    label: 'Mood Journal',
    description: 'Track daily mood & patterns',
    icon: 'happy-outline',
    route: '/tools/mood-journal',
    accent: '#F59E0B',
    badge: 'Health',
  },
  {
    id: 'calorie-counter',
    label: 'Calorie Counter',
    description: 'Quick daily calorie tracking',
    icon: 'flame-outline',
    route: '/tools/calorie-counter',
    accent: '#EF4444',
    badge: 'Health',
  },
  {
    id: 'sleep-tracker',
    label: 'Sleep Tracker',
    description: 'Log sleep & see trends',
    icon: 'moon-outline',
    route: '/tools/sleep-tracker',
    accent: '#6366F1',
    badge: 'Health',
  },
  {
    id: 'news-reader',
    label: 'News Reader',
    description: 'Browse top headlines worldwide',
    icon: 'newspaper-outline',
    route: '/tools/news-reader',
    accent: '#1D4ED8',
    badge: 'Live',
  },
  {
    id: 'wallpaper-browse',
    label: 'Wallpapers',
    description: 'Browse & save beautiful photos',
    icon: 'images-outline',
    route: '/tools/wallpaper-browse',
    accent: '#E11D48',
    badge: 'Fun',
  },
  {
    id: 'cook-tracker',
    label: 'Cook Tracker',
    description: 'Cook attendance & payment log',
    icon: 'restaurant-outline',
    route: '/tools/cook-tracker',
    accent: '#D97706',
    badge: 'Home',
  },
  {
    id: 'maid-tracker',
    label: 'Maid Tracker',
    description: 'Maid attendance & payment log',
    icon: 'home-outline',
    route: '/tools/maid-tracker',
    accent: '#7C3AED',
    badge: 'Home',
  },
  {
    id: 'milk-tracker',
    label: 'Milk Tracker',
    description: 'Daily milk delivery log',
    icon: 'water-outline',
    route: '/tools/milk-tracker',
    accent: '#0284C7',
    badge: 'Home',
  },
  {
    id: 'maintenance-tracker',
    label: 'Maintenance',
    description: 'Appliance service tracker',
    icon: 'construct-outline',
    route: '/tools/maintenance-tracker',
    accent: '#E67E22',
    badge: 'Home',
  },
  {
    id: 'water-can-tracker',
    label: 'Water Can',
    description: 'Water can delivery log',
    icon: 'water-outline',
    route: '/tools/water-can-tracker',
    accent: '#0891B2',
    badge: 'Home',
  },
  {
    id: 'flower-tracker',
    label: 'Flower Tracker',
    description: 'Daily flower delivery log',
    icon: 'flower-outline',
    route: '/tools/flower-tracker',
    accent: '#E11D48',
    badge: 'Home',
  },
  {
    id: 'driver-tracker',
    label: 'Driver Tracker',
    description: 'Driver attendance & pay',
    icon: 'car-sport-outline',
    route: '/tools/driver-tracker',
    accent: '#2563EB',
    badge: 'Home',
  },
  {
    id: 'newspaper-tracker',
    label: 'Paper Tracker',
    description: 'Newspaper delivery log',
    icon: 'newspaper-outline',
    route: '/tools/newspaper-tracker',
    accent: '#64748B',
    badge: 'Home',
  },
  {
    id: 'office-boy-tracker',
    label: 'Office Boy',
    description: 'Office boy attendance & pay',
    icon: 'person-outline',
    route: '/tools/office-boy-tracker',
    accent: '#0D9488',
    badge: 'Home',
  },
];
