export type ToolMeta = {
  id: string;
  label: string;
  description: string;
  icon: string;
  route: string;
  accent: string;
  badge: string;
};

export const TOOLS: ToolMeta[] = [
  {
    id: 'basic-calc',
    label: 'Calculator',
    description: 'Standard arithmetic',
    icon: 'calculator-outline',
    route: '/tools/basic-calculator',
    accent: '#3B82F6',
    badge: 'Math',
  },
  {
    id: 'sci-calc',
    label: 'Scientific Calc',
    description: 'Trig, log, powers & more',
    icon: 'flask-outline',
    route: '/tools/scientific-calculator',
    accent: '#6366F1',
    badge: 'Math',
  },
  {
    id: 'emi-calc',
    label: 'EMI Calculator',
    description: 'Loan EMI & schedule',
    icon: 'cash-outline',
    route: '/tools/emi-calculator',
    accent: '#10B981',
    badge: 'Finance',
  },
  {
    id: 'tip-calc',
    label: 'Tip Calculator',
    description: 'Split bills & tips',
    icon: 'restaurant-outline',
    route: '/tools/tip-calculator',
    accent: '#F59E0B',
    badge: 'Finance',
  },
  {
    id: 'unit-conv',
    label: 'Unit Converter',
    description: 'Length, weight, temp…',
    icon: 'swap-horizontal-outline',
    route: '/tools/unit-converter',
    accent: '#14B8A6',
    badge: 'Convert',
  },
  {
    id: 'color-tools',
    label: 'Color Tools',
    description: 'HEX ↔ RGB ↔ HSL',
    icon: 'color-palette-outline',
    route: '/tools/color-tools',
    accent: '#EC4899',
    badge: 'Design',
  },
  {
    id: 'todo',
    label: 'Todo Manager',
    description: 'Tasks with priorities',
    icon: 'checkbox-outline',
    route: '/tools/todo-manager',
    accent: '#8B5CF6',
    badge: 'Tasks',
  },
  {
    id: 'stopwatch',
    label: 'Stopwatch & Timer',
    description: 'Laps & countdown',
    icon: 'timer-outline',
    route: '/tools/stopwatch-timer',
    accent: '#F97316',
    badge: 'Time',
  },
  {
    id: 'password',
    label: 'Password Gen',
    description: 'Secure random passwords',
    icon: 'key-outline',
    route: '/tools/password-generator',
    accent: '#EF4444',
    badge: 'Security',
  },
  {
    id: 'bmi-calc',
    label: 'BMI Calculator',
    description: 'Body mass index',
    icon: 'body-outline',
    route: '/tools/bmi-calculator',
    accent: '#06B6D4',
    badge: 'Health',
  },
  {
    id: 'age-calc',
    label: 'Age Calculator',
    description: 'Exact age & birthday',
    icon: 'calendar-outline',
    route: '/tools/age-calculator',
    accent: '#84CC16',
    badge: 'Date',
  },
  {
    id: 'markdown',
    label: 'Markdown Notepad',
    description: 'Write & preview notes',
    icon: 'document-text-outline',
    route: '/tools/markdown-notepad',
    accent: '#64748B',
    badge: 'Notes',
  },
  {
    id: 'notes',
    label: 'Note Cards',
    description: 'Colorful notes with PIN lock',
    icon: 'reader-outline',
    route: '/tools/notes',
    accent: '#F59E0B',
    badge: 'Notes',
  },
  {
    id: 'weather',
    label: 'Weather',
    description: 'Live weather & 7-day forecast',
    icon: 'partly-sunny-outline',
    route: '/tools/weather',
    accent: '#3B82F6',
    badge: 'Live',
  },
  {
    id: 'investment',
    label: 'Investment Calc',
    description: 'SIP, lumpsum, returns & compare',
    icon: 'trending-up-outline',
    route: '/tools/investment-calculator',
    accent: '#10B981',
    badge: 'Finance',
  },
  {
    id: 'birthday',
    label: 'Birthday Tracker',
    description: 'Never miss a birthday',
    icon: 'gift-outline',
    route: '/tools/birthday-tracker',
    accent: '#F43F5E',
    badge: 'Life',
  },
  {
    id: 'holiday',
    label: 'Holiday Calendar',
    description: 'Holidays & custom events',
    icon: 'flag-outline',
    route: '/tools/holiday-calendar',
    accent: '#8B5CF6',
    badge: 'Calendar',
  },
  {
    id: 'gym',
    label: 'Gym Calendar',
    description: 'Track your workout days',
    icon: 'barbell-outline',
    route: '/tools/gym-calendar',
    accent: '#F97316',
    badge: 'Health',
  },
  {
    id: 'water',
    label: 'Water Tracker',
    description: 'Daily hydration goals',
    icon: 'water-outline',
    route: '/tools/water-tracker',
    accent: '#0EA5E9',
    badge: 'Health',
  },
  {
    id: 'expense',
    label: 'Expense Tracker',
    description: 'Track spending & budgets',
    icon: 'wallet-outline',
    route: '/tools/expense-tracker',
    accent: '#6366F1',
    badge: 'Finance',
  },
  {
    id: 'reminder',
    label: 'Reminders',
    description: 'Set reminders & alerts',
    icon: 'notifications-outline',
    route: '/tools/reminder',
    accent: '#A855F7',
    badge: 'Life',
  },
  {
    id: 'translate',
    label: 'Translate',
    description: 'Translate text between languages',
    icon: 'language-outline',
    route: '/tools/translate',
    accent: '#D946EF',
    badge: 'Language',
  },
];
